document.getElementsByClassName('form-control-sm')[0].value = 'DS 7 Stops';
document.getElementsByClassName('form-control-sm')[1].value = '3';
document.getElementsByClassName('form-control-sm')[2].value = '120';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[2].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.51325';
document.getElementsByClassName('form-control-sm')[1].value = '120.99068';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.50903';
document.getElementsByClassName('form-control-sm')[1].value = '120.99365';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.539207227926902';
document.getElementsByClassName('form-control-sm')[1].value = '120.98977745396049';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.534694794656243';
document.getElementsByClassName('form-control-sm')[1].value = '120.99434626437592';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.539741525871644';
document.getElementsByClassName('form-control-sm')[1].value = '120.99777964043429';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.535203133158655';
document.getElementsByClassName('form-control-sm')[1].value = '121.00241449772616';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.551433092443729';
document.getElementsByClassName('form-control-sm')[1].value = '121.02656109759592';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.546926094659344';
document.getElementsByClassName('form-control-sm')[1].value = '121.03008015591014';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.570669866006527';
document.getElementsByClassName('form-control-sm')[1].value = '121.04367915508293';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.56630423548145';
document.getElementsByClassName('form-control-sm')[1].value = '121.0483283486605';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.589016713864568';
document.getElementsByClassName('form-control-sm')[1].value = '121.05411464043465';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.584718146716531';
document.getElementsByClassName('form-control-sm')[1].value = '121.05876022656285';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.610785707237877';
document.getElementsByClassName('form-control-sm')[1].value = '121.0537886770124';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.606674442899923';
document.getElementsByClassName('form-control-sm')[1].value = '121.05845572081326';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.61595968222573';
document.getElementsByClassName('form-control-sm')[1].value = '121.05139196927097';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.611848514671594';
document.getElementsByClassName('form-control-sm')[1].value = '121.0560482842355';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.630459228241007';
document.getElementsByClassName('form-control-sm')[1].value = '121.04471516927117';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.626327569795327';
document.getElementsByClassName('form-control-sm')[1].value = '121.04937148423572';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.643531658062017';
document.getElementsByClassName('form-control-sm')[1].value = '121.03691366927139';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.63974280301566';
document.getElementsByClassName('form-control-sm')[1].value = '121.04158071307226';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.653366694064948';
document.getElementsByClassName('form-control-sm')[1].value = '121.03051896927136';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.649526108739387';
document.getElementsByClassName('form-control-sm')[1].value = '121.03517528423589';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.659973665079784';
document.getElementsByClassName('form-control-sm')[1].value = '121.0171412692482';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.655468891304901';
document.getElementsByClassName('form-control-sm')[1].value = '121.02179758421273';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.659733608199652';
document.getElementsByClassName('form-control-sm')[1].value = '121.00283306927132';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.655228829488141';
document.getElementsByClassName('form-control-sm')[1].value = '121.00748938423587';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.659598189259533';
document.getElementsByClassName('form-control-sm')[1].value = '120.99494776927135';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.655093407763232';
document.getElementsByClassName('form-control-sm')[1].value = '120.9996040842359';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-info')[0].click();

document.getElementsByClassName('form-control-sm')[0].value = '14.659437711214382';
document.getElementsByClassName('form-control-sm')[1].value = '120.98381856927128';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('form-control-sm')[0].value = '14.654932926404847';
document.getElementsByClassName('form-control-sm')[1].value = '120.98847488423584';
document.getElementsByClassName('form-control-sm')[0].dispatchEvent(new Event('input'));
document.getElementsByClassName('form-control-sm')[1].dispatchEvent(new Event('input'));
document.getElementsByClassName('btn btn-outline-info')[0].click();
document.getElementsByClassName('btn btn-outline-primary')[0].click();

